# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      - image: circleci/mongo:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    environment:
      - mongoose__uri: "mongodb://localhost:27017/data"


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

  deploy:
    steps:
      - run: bash .circleci/setup-heroku.sh
    - add_ssh_keys:
        fingerprints:
          - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
    - run: |
          git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
          heroku run python manage.py deploy
          heroku restart

 workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master
